# Generated by Django 2.2.17 on 2021-06-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'notice', 'verbose_name_plural': 'notice'},
        ),
        migrations.AlterField(
            model_name='user',
            name='auth',
            field=models.CharField(max_length=10, null=True, verbose_name='auth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=128, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hp',
            field=models.IntegerField(null=True, unique=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('3', 'Lv3_미인증사용자'), ('2', 'Lv2_인증사용자'), ('1', 'Lv1_관리자'), ('0', 'Lv0_개발자')], default=3, max_length=18, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='PW'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=20, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=8, null=True, verbose_name='username'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='notice',
        ),
    ]
