# Generated by Django 2.2.17 on 2021-07-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('type', models.TextField(blank=True, null=True, verbose_name='type')),
                ('applicant', models.TextField(verbose_name='applicant')),
                ('date', models.TextField(verbose_name='applicant')),
            ],
            options={
                'verbose_name': 'Intellectual Property',
                'verbose_name_plural': 'Intellectual Property',
                'db_table': 'ip',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('journals', models.TextField(verbose_name='journals')),
                ('issued_date', models.TextField(verbose_name='issued_date')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journal',
                'db_table': 'journal',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('content', models.TextField(verbose_name='content')),
                ('email', models.TextField(verbose_name='email')),
                ('img_upload', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
            options={
                'verbose_name': 'People',
                'verbose_name_plural': 'People',
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professor',
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('publisher', models.TextField(verbose_name='publisher')),
                ('published_date', models.TextField(verbose_name='published_date')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publication',
                'db_table': 'publication',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='title')),
                ('img', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Research',
                'db_table': 'research',
            },
        ),
        migrations.CreateModel(
            name='rp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('org', models.TextField(blank=True, null=True, verbose_name='org')),
                ('period', models.TextField(verbose_name='period')),
            ],
            options={
                'verbose_name': 'Research & Project',
                'verbose_name_plural': 'Research & Project',
                'db_table': 'rp',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('content', models.TextField(verbose_name='content')),
                ('email', models.TextField(verbose_name='email')),
                ('img_upload', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
            },
        ),
    ]
