# Generated by Django 2.2.17 on 2021-10-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domestic_Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('journals', models.TextField(verbose_name='journals')),
                ('issued_date', models.TextField(verbose_name='issued_date')),
            ],
            options={
                'verbose_name': 'Domestic Journal',
                'verbose_name_plural': 'Domestic Journal',
                'db_table': 'domestic_journal',
            },
        ),
        migrations.CreateModel(
            name='International_Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('journals', models.TextField(verbose_name='journals')),
                ('issued_date', models.TextField(verbose_name='issued_date')),
            ],
            options={
                'verbose_name': 'International Journal',
                'verbose_name_plural': 'International Journal',
                'db_table': 'international_journal',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='title')),
                ('img', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('content', models.TextField(verbose_name='content')),
                ('left_right_check', models.BooleanField(verbose_name='left_right_check')),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Research',
                'db_table': 'research',
            },
        ),
    ]
