# Generated by Django 2.2.17 on 2021-10-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('content', models.TextField(verbose_name='content')),
                ('email', models.TextField(verbose_name='email')),
                ('img_upload', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('delimiter', models.IntegerField(verbose_name='delimiter')),
            ],
            options={
                'verbose_name': 'People',
                'verbose_name_plural': 'People',
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professor',
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('content', models.TextField(verbose_name='content')),
                ('email', models.TextField(verbose_name='email')),
                ('img_upload', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
            },
        ),
    ]
